; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = stlink         ; keep in mind which upload protocol youre using, if you have a different one, change it here
;upload_flags = -d 0483:df11

; --- ADD THESE TWO LINES TO FORCE UNLOCK & ERASE ---

   

;build_flags = -O2
;build_type = release

;comment out which main file you want to use, the other ones will be ignored by the build system
;build_src_filter = -<*> +<bitbang_main/100mus_speedcycle/crisscross_main.cpp>  ; change the test mainfile here ; for crisscross_main.cpp at 100 mus
;build_src_filter = -<*> +<bitbang_main/5mus_speedcycle/first_test_main.cpp>  ; for first_test_main.cpp at 5mus
;build_src_filter = -<*> +<bitbang_main/100mus_speedcycle/crisscross_2_main.cpp> ; for crisscross_2_main.cpp at 100 mus 
;build_src_filter = -<*> +<bitbang_main/5mus_speedcycle/full_output_main.cpp> ; for full_output_main.cpp at 5mus
;build_src_filter = -<*> +<bitbang_main/5mus_speedcycle/full_input_main.cpp> ; for full_input_main.cpp at 5 mus
;build_src_filter = -<*> +<bitbang_main/5mus_speedcycle/full_io_main.cpp> ; for full_io_main.cpp at 5 mus
;build_src_filter = -<*> +<main.cpp>  ; for main.cpp at 5 mus
build_src_filter = -<*> +<bitbang_main/5mus_speedcycle/crisscross_5mus_main.cpp> +<configs/sysclk.cpp> ; for crisscross_main.cpp at 5mus